apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: schedules.kubeflow.org
spec:
  group: kubeflow.org
  version: v1alpha1
  names:
    kind: Schedule
    plural: schedules
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            replicas:
              type: integer
              minimum: 1
              maximum: 10

# TODO: Add validation
# See https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/
# This feature is beta in kubernetes v1.9